# Generated by Django 5.1 on 2026-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Followed up (1)', 'Followed up (1)'), ('Followed up (2)', 'Followed up (2)'), ('Followed up (3)', 'Followed up (3)'), ('Followed up (4)', 'Followed up (4)'), ('Invited to first interview', 'Invited to first interview'), ('Invited to second interview', 'Invited to second interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Rejected after first interview', 'Rejected after first interview'), ('Closed / No interest', 'Closed / No interest'), ('No response', 'No response')], default='Applied', max_length=50),
        ),
    ]
