# Generated by Django 5.1 on 2026-04-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
