# Generated by Django 5.1 on 2026-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
