# Generated by Django 5.1 on 2026-04-17 18:37

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), jobs.models.validate_pdf_size]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Applied', 'Applied'), ('Followed up (1)', 'Followed up (1)'), ('Followed up (2)', 'Followed up (2)'), ('Followed up (3)', 'Followed up (3)'), ('Followed up (4)', 'Followed up (4)'), ('Invited to first interview', 'Invited to first interview'), ('Invited to second interview', 'Invited to second interview'), ('Technical Test', 'Technical Test'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Rejected after first interview', 'Rejected after first interview'), ('Closed / No interest', 'Closed / No interest'), ('No response', 'No response')], db_index=True, default='New', max_length=50),
        ),
    ]
